train_dataset_name: "./data/train_total_im-patient.csv"
test_dataset_name: "./data/test_dataset_total_im-patient.csv"
test_label_name: "./data/test_label_total_im-patient.csv"

answer_label_name: "./answer/total_im_model_with_labels.csv"
model_name: "./save_models/model_total_im.pt"
answer_csv_name: "./answer/total_im_model.csv"

label: 4
wandb: True
